export const lessons = [
  [
    /* Lesson Title */ "Lesson 1: MakeCode Basics",
    /* Lesson Objective */ "In this lesson, we'll learn about this class, how to access MakeCode Arcade, and create a sprite.",
    /* href */ "/lesson1",
    /* Firestore field */ "Lesson1",
    /* Due Date */ "3/20/24",
  ],
  [
    /* Lesson Title */ "Lesson 2: Sprite Creation & Position",
    /* Lesson Objective */ "In this lesson, we'll learn how to create the background and the sprites in our game and position them on-screen.",
    /* href */ "/lesson2",
    /* Firestore field */ "Lesson2",
    /* Due Date */ "3/21/24",
  ],
  [
    /* Lesson Title */ "Lesson 3: Velocity & Pauses",
    /* Lesson Objective */ "In this lesson, we'll learn how to use velocity methods to have our sprites move and pauses to help time their movements.",
    /* href */ "/lesson3",
    /* Firestore field */ "Lesson3",
    /* Due Date */ "3/22/24",
  ],
  [
    /* Lesson Title */ "Lesson 4: Text Elements & Animations",
    /* Lesson Objective */ "In this lesson, we'll learn how to create text boxes and splashes to add story components to our game, as well as, how to create, start, and stop animations for sprites.",
    /* href */ "/lesson4",
    /* Firestore field */ "Lesson4",
    /* Due Date */ "3/25/24",
  ],
  [
    /* Lesson Title */ "Unit 1 Project: Sprite Story",
    /* Lesson Objective */ "In this project, we'll combine what we know about positioning, velcoity, story elements, and animations to create a short story.",
    /* href */ "/project1",
    /* Firestore field */ "SpriteStory",
    /* Due Date */ "3/31/24",
  ],
  [
    /* Lesson Title */ "Lesson 5: Events & Event Handlers",
    /* Lesson Objective */ "In this lesson, we'll learn how to use event handlers to allow user input and program what should happen as different events occur",
    /* href */ "/lesson5",
    /* Firestore field */ "Lesson5",
    /* Due Date */ "4/1/24",
  ],
  [
    /* Lesson Title */ "Lesson 6: SpriteKinds",
    /* Lesson Objective */ "In this lesson, we'll use SpriteKinds to help us define interactions between different sprites better.",
    /* href */ "/lesson6",
    /* Firestore field */ "Lesson6",
    /* Due Date */ "4/2/24",
  ],
  [
    /* Lesson Title */ "Lesson 7: Life & Score",
    /* Lesson Objective */ "In this lesson, we'll learn how to use and control numerical variables like Life & Score",
    /* href */ "/lesson7",
    /* Firestore field */ "Lesson7",
    /* Due Date */ "4/3/24",
  ],
  [
    /* Lesson Title */ "Lesson 8: Multiplayer",
    /* Lesson Objective */ "In this lesson, we'll learn how to add multiplayer components to our game.",
    /* href */ "/lesson8",
    /* Firestore field */ "Lesson8",
    /* Due Date */ "4/4/24",
  ],
  [
    /* Lesson Title */ "Unit 2 Project: Scroller Games",
    /* Lesson Objective */ "In this project, we'll combine what we know about event handlers, numerical variables, and SpriteKinds to create an arcade game.",
    /* href */ "/project2",
    /* Firestore field */ "ScrollerGame",
    /* Due Date */ "4/10/24",
  ],
  [
    /* Lesson Title */ "Lesson 9: Tilemaps & Tile Overlap Events",
    /* Lesson Objective */ "In this lesson, we'll learn about tilemaps, how to create them, and how to create events when we reach certain tiles.",
    /* href */ "/lesson9",
    /* Firestore field */ "Lesson9",
    /* Due Date */ "4/11/24",
  ],
  [
    /* Lesson Title */ "Lesson 10: Loops",
    /* Lesson Objective */ "In this lesson, we'll learn about Repeat loops and For Index loops and how we can use them to simplify our programming.",
    /* href */ "/lesson10",
    /* Firestore field */ "Lesson10",
    /* Due Date */ "4/12/24",
  ],
  [
    /* Lesson Title */ "Lesson 11: Arrays",
    /* Lesson Objective */ "In this lesson, we'll learn about arrays (also called lists) and how they can help us create our levels quickly and efficiently.",
    /* href */ "/lesson11",
    /* Firestore field */ "Lesson11",
    /* Due Date */ "4/15/24",
  ],
  [
    /* Lesson Title */ "Lesson 12: Boolean Variables & Power Ups",
    /* Lesson Objective */ "In this lesson, we'll learn about Boolean variables and basic If statements.",
    /* href */ "/lesson12",
    /* Firestore field */ "Lesson12",
    /* Due Date */ "4/16/24",
  ],
  [
    /* Lesson Title */ "Lesson 13: If-Else Statements and Conditions",
    /* Lesson Objective */ "In this lesson, we'll learn how to use If-Else statements and conditions with Boolean variables to selectively choose which parts of our code will run.",
    /* href */ "/lesson13",
    /* Firestore field */ "Lesson13",
    /* Due Date */ "4/17/24",
  ],
  [
    /* Lesson Title */ "Lesson 14: Sprite Characteristics & Movement",
    /* Lesson Objective */ "In this lesson, we'll learn about using arrays, loops, and conditional statements together to make really complex behavior for our sprites.",
    /* href */ "/lesson14",
    /* Firestore field */ "Lesson14",
    /* Due Date */ "4/18/24",
  ],
  [
    /* Lesson Title */ "Lesson 15: Functions",
    /* Lesson Objective */ "In this lesson, we'll learn how to create and call functions to reuse parts of our code more easily.",
    /* href */ "/lesson15",
    /* Firestore field */ "Lesson15",
    /* Due Date */ "4/19/24",
  ],
  [
    /* Lesson Title */ "Lesson 16: Boss Battle",
    /* Lesson Objective */ "In this lesson, we'll plan out how to create an exciting boss battle to add to our game.",
    /* href */ "/lesson16",
    /* Firestore field */ "Lesson16",
    /* Due Date */ "4/22/24",
  ],
  [
    /* Lesson Title */ "Unit 3 Project: Platformer Games",
    /* Lesson Objective */ "In this lesson, we'll combine what we know about conditional statements, loops, arrays, and functions to create a platformer game.",
    /* href */ "/project3",
    /* Firestore field */ "PlatformerGame",
    /* Due Date */ "4/29/24",
  ],
  [
    /* Lesson Title */ "Lesson 17: World Creation",
    /* Lesson Objective */ "In this lesson, we'll create an overworld for our Adventure Game Project and populate it with enemies, items, and objects",
    /* href */ "/lesson17",
    /* Firestore field */ "Lesson17",
    /* Due Date */ "5/1/24",
  ],
  [
    /* Lesson Title */ "Lesson 18: Attacking",
    /* Lesson Objective */ "In this lesson, we'll add a short-range method of attacking for our player character to defeat enemies.",
    /* href */ "/lesson18",
    /* Firestore field */ "Lesson18",
    /* Due Date */ "5/3/24",
  ],
  [
    /* Lesson Title */ "Lesson 19: Limited Projectiles",
    /* Lesson Objective */ "In this lesson, we'll add the ability to shoot projectiles and have limited ammunition to our Adventure Game.",
    /* href */ "/lesson19",
    /* Firestore field */ "Lesson19",
    /* Due Date */ "5/7/24",
  ],
  [
    /* Lesson Title */ "Lesson 20: Entries & Exits",
    /* Lesson Objective */ "In this lesson, we'll add more places to explore than just the overworld in our Adventure Game.",
    /* href */ "/lesson20",
    /* Firestore field */ "Lesson20",
    /* Due Date */ "5/9/24",
  ],
  [
    /* Lesson Title */ "Lesson 21: Boss Battle with Weak Point",
    /* Lesson Objective */ "In this lesson, we'll create a boss battle that has a weak point similar to many classic games.",
    /* href */ "/lesson21",
    /* Firestore field */ "Lesson21",
    /* Due Date */ "5/13/24",
  ],
  [
    /* Lesson Title */ "Unit 4 Project: Adventure Game",
    /* Lesson Objective */ "In this project, we'll combine what we know about conditional statements, loops, arrays, and functions to create an adventure game.",
    /* href */ "/project4",
    /* Firestore field */ "Project4",
    /* Due Date */ "5/16/24",
  ],
  [
    /* Lesson Title */ "Unit 5 Project: Your Game!",
    /* Lesson Objective */ "In this project, you'll design and develop your own game using everything that we've learned throughout this course.",
    /* href */ "/project5",
    /* Firestore field */ "FinalGame",
    /* Due Date */ "6/5/24",
  ],
];
